export const User = {
    LOGIN_START: "USER_LOGIN_START",
    LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    LOGIN_FAIL: "USER_LOGIN_FAIL",
    LOGOUT: "USER_LOGOUT"
};

export const Article = {
    POST_LOADING: "ARTICLE_POST",
    POST_SUCCESS: "ARTICLE_POST_SUCCESS",
    POST_FAIL: "ARTICLE_POST_FAIL",

    GET_LOADING: "ARTICLE_FETCH_LOADING",
    GET_LOADING_SUCCESS: "ARTICLE_FETCH_LOADING_SUCCESS",
    GET_LOADING_FAIL: "ARTICLE_FETCH_LOADING_FAIL",

    GET_BY_CATEGORY_LOADING: "ARTICLE_FETCH_BY_CATEGORY_LOADING",
    GET_BY_CATEGORY_LOADING_SUCCESS: "ARTICLE_FETCH_BY_CATEGORY_LOADING_SUCCESS",
    GET_BY_CATEGORY_LOADING_FAIL: "ARTICLE_FETCH_BY_CATEGORY_LOADING_FAIL",

    GET_ONE_LOADING: "ARTICLE_FETCH_DETAIL_LOADING",
    GET_ONE_LOADING_SUCCESS: "ARTICLE_FETCH_DETAIL_LOADING_SUCCESS",
    GET_ONE_LOADING_FAIL: "ARTICLE_FETCH_DETAIL_LOADING_FAIL",

    UPDATE_LOADING: "ARTICLE_UPDATE",
    UPDATE_SUCCESS: "ARTICLE_UPDATE_SUCCESS",
    UPDATE_FAIL: "ARTICLE_UPDATE_FAIL",
};

export const Category = {
    POST_LOADING: "CATEGORY_POST",
    POST_SUCCESS: "CATEGORY_POST_SUCCESS",
    POST_FAIL: "CATEGORY_POST_FAIL",

    GET_LOADING: "CATEGORY_FETCH_LOADING",
    GET_LOADING_SUCCESS: "CATEGORY_FETCH_LOADING_SUCCESS",
    GET_LOADING_FAIL: "CATEGORY_FETCH_LOADING_FAIL",

    GET_ONE_LOADING: "CATEGORY_FETCH_DETAIL_LOADING",
    GET_ONE_LOADING_SUCCESS: "CATEGORY_FETCH_DETAIL_LOADING_SUCCESS",
    GET_ONE_LOADING_FAIL: "CATEGORY_FETCH_DETAIL_LOADING_FAIL"
};